// XML.bnf
{
  parserClass="com.example.XMLParser"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"
 // extends="com.intellij.lang.parser.GeneratedParserUtilBase"

  psiClassPrefix="XML"
  psiImplClassSuffix="Impl"
  elementTypeHolderClass="com.example.XMLElementTypes"
  elementTypeClass="de.brand.lexertest.XMLElementType"
  tokenTypeClass="de.brand.lexertest.XMLTokenType"
  tokens = [
      XML_DECL_START = "<?xml"
      XML_DECL_END = "?>"
      COMMENT_START = "<!--"
      COMMENT_END = "-->"
      TAG_OPEN = "<"
      TAG_CLOSE = ">"
      TAG_OPEN_CLOSE = "</"
      TAG_SELF_CLOSE = "/>"
      EQUALS = "="
      DOUBLE_QUOTE = "\""
      ELEMENT_NAME = "regexp:/[:_a-zA-Z][_a-zA-Z0-9.-]*/"
      ATTRIBUTE_VALUE = "regexp:/[^\"]*/"
      ENCLOSED_TEXT_TOKEN = "regexp:/((\\.)|[^<&\"])+/"
    ]
}


root ::= xml_document

xml_document ::= declaration_opt? element

declaration_opt ::= XML_DECL_START attribute_list XML_DECL_END
                  | /* empty */

element ::= element_start_token element_content? element_end_token
          | element_self_close_token

element_start_token ::= TAG_OPEN ELEMENT_NAME attribute_list? TAG_CLOSE
element_end_token ::= TAG_OPEN_CLOSE ELEMENT_NAME TAG_CLOSE
element_self_close_token ::= TAG_OPEN ELEMENT_NAME attribute_list? TAG_SELF_CLOSE

element_content ::= element_list+
                  | ENCLOSED_TEXT_TOKEN
                  | /* empty */

element_list ::= element
               | comment

attribute_list ::= attribute+
                 | /* empty */

attribute ::= ELEMENT_NAME EQUALS attribute_string
attribute_string ::= DOUBLE_QUOTE ATTRIBUTE_VALUE DOUBLE_QUOTE
//enclosed_text ::=

comment ::= COMMENT_START COMMENT_END